version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/sandbox/browser-web-v1"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
