import Link from "next/link";
import { categoryLabels } from "@/lib/domain/catalog";
import { ShowcaseCard } from "./components/ShowcaseCard";
import { RunCard } from "./components/RunCard";
import { SiteHeader } from "./components/SiteHeader";
import { SiteFooter } from "./components/SiteFooter";
import { listPublicShowcaseCards } from "@/lib/data/showcases";
import { listAggregateLeaderboard } from "@/lib/data/leaderboards";
import { listRecentPublicRuns } from "@/lib/data/runs";
import { listPublicBenchmarkVersions } from "@/lib/data/public-catalog";

export default async function Home() {
  const scopes = [
    ["overall", "Overall"],
    ["frontend", "Frontend"],
    ["browser-game", "Browser games"],
    ["browser-3d", "Browser 3D"],
  ] as const;
  const [databaseFeedResult, recentRuns, aggregateSets, benchmarkVersionsResult] =
    await Promise.all([
      listPublicShowcaseCards(6).catch(() => null),
      listRecentPublicRuns(3).catch(() => []),
      Promise.all(
        scopes.map(([scope]) =>
          listAggregateLeaderboard(scope).catch(() => []),
        ),
      ),
      listPublicBenchmarkVersions().catch(() => null),
    ]);
  const databaseFeed = databaseFeedResult ?? [];
  const benchmarkVersions = benchmarkVersionsResult ?? [];
  const publicTestsUnavailable = databaseFeedResult === null;
  const benchmarkCatalogUnavailable = benchmarkVersionsResult === null;
  const latestShowcase = databaseFeed[0];
  const coverage = new Map<string, Set<string>>();
  for (const version of benchmarkVersions) {
    const entries = coverage.get(version.category) ?? new Set<string>();
    entries.add(version.slug);
    coverage.set(version.category, entries);
  }
  const activeBenchmarkCategoryCount = scopes
    .filter(([scope]) => scope !== "overall")
    .filter(([scope]) => (coverage.get(scope)?.size ?? 0) > 0).length;
  return (
    <div className="site-shell">
      <SiteHeader />
      <main>
        <section className="hero section-wrap">
          <div className="hero-copy">
            <div className="eyebrow">
              <span className="live-dot" aria-hidden="true" />
              Real model tests. Public evidence.
            </div>
            <h1>
              See what models
              <br />
              <span>actually built.</span>
            </h1>
            <p className="hero-intro">
              Benchmax records the prompt, source code, video, settings, and
              failures behind every test. Community uploads stay separate from
              rankings, which use only runs generated by Benchmax.
            </p>
            <div className="hero-actions">
              <Link className="button button-primary" href="/upload">
                Upload a test <span aria-hidden="true">→</span>
              </Link>
              <Link className="button button-secondary" href="/methodology">
                Read the methodology
              </Link>
            </div>
            <div className="hero-proof" aria-label="Benchmax trust principles">
              <span>Public evidence</span>
              <span>Exact configurations</span>
              <span>Reproducible scoring</span>
            </div>
          </div>

          <aside className="hero-panel" aria-label="Latest test snapshot">
            <div className="panel-topline">
              <span>LATEST PUBLIC RECORD</span>
              <span>
                {latestShowcase
                  ? "COMMUNITY TEST"
                  : publicTestsUnavailable
                    ? "RECORDS UNAVAILABLE"
                    : "AWAITING FIRST TEST"}
              </span>
            </div>
            <div className="hero-record">
              <span className="section-index">
                {latestShowcase
                  ? categoryLabels[latestShowcase.category]
                  : "PUBLIC EVIDENCE"}
              </span>
              <strong>
                {latestShowcase?.title ??
                  (publicTestsUnavailable
                    ? "Public test records are temporarily unavailable."
                    : "No community tests have been published yet.")}
              </strong>
              <p>
                {latestShowcase?.description ??
                  (publicTestsUnavailable
                    ? "Benchmax will not substitute sample evidence while the public catalog cannot be read."
                    : "The first approved test will appear here with its real model, harness, reasoning level, and evidence record.")}
              </p>
            </div>
            <div className="panel-result">
              <div>
                <span className="result-label">MODEL</span>
                <strong>{latestShowcase?.model ?? "—"}</strong>
              </div>
              <div>
                <span className="result-label">HARNESS</span>
                <strong>{latestShowcase?.harness ?? "—"}</strong>
              </div>
              <div>
                <span className="result-label">REASONING</span>
                <strong>{latestShowcase?.reasoning ?? "—"}</strong>
              </div>
            </div>
            <div className="panel-foot">
              <span>
                {latestShowcase
                  ? latestShowcase.evidence.join(" + ") || "No public artifacts"
                  : publicTestsUnavailable
                    ? "No substitute records"
                    : "Nothing is shown until approval"}
              </span>
              <span className="status-pill neutral">
                {latestShowcase ? "Not ranked" : "No record"}
              </span>
            </div>
          </aside>
        </section>

        <section className="rankings section-wrap" id="rankings">
          <div className="section-heading">
            <div>
              <span className="section-index">01 / LEADERBOARDS</span>
              <h2>Rankings you can inspect.</h2>
            </div>
            <p>
              Every row is one exact model, endpoint, harness, reasoning
              level, and settings hash. No silent merging.
            </p>
          </div>

          <div className="ranking-board">
            <div className="ranking-head">
              <span>Category</span>
              <span>Leader</span>
              <span>Coverage</span>
              <span>Status</span>
            </div>
            {scopes.map(([scope, label], index) => {
              const row = aggregateSets[index][0];
              return (
              <div className="ranking-row" key={scope}>
                <div className="ranking-category">
                  <span className="rank-number">{row ? "1" : "—"}</span>
                  <strong>{label}</strong>
                </div>
                <span className={row ? undefined : "muted"}>
                  {row
                    ? `${row.model_name} · ${row.reasoning_level}`
                    : "Waiting for platform runs"}
                </span>
                <span className="mono">
                  {row
                    ? `${(row.score_bps / 100).toFixed(2)} · ${row.total_run_count} runs`
                    : benchmarkCatalogUnavailable
                      ? "Coverage unavailable"
                    : scope === "overall"
                      ? `0 / ${activeBenchmarkCategoryCount} categories`
                      : `0 / ${coverage.get(scope)?.size ?? 0} benchmarks`}
                </span>
                <span
                  className={`status-pill ${
                    row && !row.provisional ? "approved" : "pending"
                  }`}
                >
                  {row
                    ? row.provisional
                      ? "Provisional"
                      : "Established"
                    : "Awaiting runs"}
                </span>
              </div>
            )})}
            <div className="ranking-note">
              <span>Why is the board empty?</span>
              <p>
                Uploaded tests never affect rankings. The board activates only
                after Benchmax generates, executes, and scores eligible runs.
              </p>
              <Link href="/methodology">How verification works →</Link>
            </div>
          </div>
        </section>

        <section className="latest section-wrap">
          <div className="section-heading compact">
            <div>
              <span className="section-index">02 / PLATFORM RUNS</span>
              <h2>Generated, executed, and scored here.</h2>
            </div>
            <Link className="text-link" href="/leaderboards">
              Open leaderboards →
            </Link>
          </div>
          {recentRuns.length > 0 ? (
            <div className="card-grid">
              {recentRuns.map((run) => (
                <RunCard key={run.id} run={run} />
              ))}
            </div>
          ) : (
            <div className="empty-state">
              <strong>No published platform runs yet.</strong>
              <p>
                The board stays empty until generation, execution, and scoring
                complete under the frozen contract.
              </p>
              <Link className="button button-primary" href="/run">
                Launch the first run
              </Link>
            </div>
          )}
        </section>

        <section className="latest section-wrap">
          <div className="section-heading compact">
            <div>
              <span className="section-index">03 / COMMUNITY TESTS</span>
              <h2>Everything needed to inspect the claim.</h2>
            </div>
            <Link className="text-link" href="/explore">
              Explore all tests →
            </Link>
          </div>
          {databaseFeed.length > 0 ? (
            <div className="card-grid">
              {databaseFeed.map((showcase) => (
                <ShowcaseCard key={showcase.id} showcase={showcase} />
              ))}
            </div>
          ) : (
            <div className="empty-state">
              <strong>
                {publicTestsUnavailable
                  ? "Public test records are temporarily unavailable."
                  : "No published community tests yet."}
              </strong>
              <p>
                {publicTestsUnavailable
                  ? "No sample submissions are shown in place of unavailable records."
                  : "Approved uploads will appear here with their real prompt, configuration, contributor, and evidence."}
              </p>
              {!publicTestsUnavailable && (
                <Link className="button button-primary" href="/upload">
                  Upload the first test
                </Link>
              )}
            </div>
          )}
        </section>

        <section className="protocol section-wrap">
          <div className="protocol-card">
            <div className="protocol-copy">
              <span className="section-index">04 / TWO TRACKS</span>
              <h2>Share freely. Rank carefully.</h2>
              <p>
                Your existing Cursor, Codex, Claude Code, or custom-harness work
                belongs here as a public test report. Ranked benchmark runs are
                different: Benchmax controls every generation attempt.
              </p>
            </div>
            <div className="track-list">
              <div className="track">
                <span className="track-number">A</span>
                <div>
                  <strong>Community test</strong>
                  <p>Any real test, clearly labeled and kept out of rankings.</p>
                </div>
                <span className="track-state">Open now</span>
              </div>
              <div className="track">
                <span className="track-number">B</span>
                <div>
                  <strong>Platform-generated run</strong>
                  <p>
                    Pinned prompt, harness, environment, attempts, and scoring.
                  </p>
                </div>
                <span className="track-state">Ready when configured</span>
              </div>
            </div>
          </div>
        </section>

        <section className="category-strip section-wrap">
          {Object.entries(categoryLabels).map(([key, label], index) => (
            <Link href={`/explore?category=${key}`} key={key}>
              <span>0{index + 1}</span>
              <strong>{label}</strong>
              <span>
                {key === "other"
                  ? "Community tests"
                  : benchmarkCatalogUnavailable
                    ? "Catalog unavailable"
                    : `${coverage.get(key)?.size ?? 0} benchmarks`} →
              </span>
            </Link>
          ))}
        </section>

        <section className="closing-cta section-wrap">
          <p>Have a model test sitting in a folder?</p>
          <h2>Make the evidence easy to inspect.</h2>
          <Link className="button button-primary" href="/upload">
            Upload a test <span aria-hidden="true">→</span>
          </Link>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
